### PR TITLE
Adds direct link to the landing page so that side TOC works better

### PR DESCRIPTION
**Pull request by annegentle**
Fixes Issue #408

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-0253d849a1/docs/user-guides/infrastructure/)

**Comment by annegentle** [comment]
Okay, this doesn't quite fix the Issue completely so I'll keep looking at it.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-5914ef6b64/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-5914ef6b64/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-5914ef6b64/docs/user-guides/infrastructure/). :bow:

**Pull request closed without merging**
