### PR TITLE
Fix dead link 

### PR DESCRIPTION
**Pull request by donnorton**
Fix dead link to "Controlling network traffic by using security groups and rules" document

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-a0ad6862a0/docs/user-guides/infrastructure/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-62e8b29141/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-30d254ad46/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-761adc88ca/docs/user-guides/infrastructure/)

**Comment by cyrichardson** [comment]
Thanks, @donnorton! I'm merging your fix and added my fix to it for another dead link.
Sorry it took so long to do this merge.

**Pull request merged**
