### PR TITLE
Update image size per Todd Archer

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 28 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-cf558aa99/docs/user-guides/infrastructure/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 30 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-917ff6808/docs/user-guides/infrastructure/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 32 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-057f88be3/docs/user-guides/infrastructure/). valid for 14 days

**Comment by rackernexus** [comment]
Build 34 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3ba457859/docs/user-guides/infrastructure/). valid for 14 days

**Pull request merged**
