### PR TITLE
Removed obsolete _toc.rst to avoid confusion.

### PR DESCRIPTION
**Pull request by meker12**
The _toc.rst file isn't being used anymore.  We removed it from the API dev guides to avoid confusing people.  Maybe you would like to do the same.  Thx!

### CODE REVIEW

**Comment by rose-coste** [comment]
@ktbartholomew added _toc.rst to give us a left-side TOC. I understand this works differently for userguides than it does for devguides. I can't do a local deconst build to confirm that this userguide has good left-side navigation without _toc.rst. @ktbartholomew, can you confirm deleting _toc.rst would be a good thing?

**Comment by ktbartholomew** [comment]
**DO NOT MERGE**

Removing `_toc.rst` from this repo would break the left-side navigation. The way this repo is rendered and the way the dev guides are rendered are very different, because this is a multi-page book, whereas the dev guides are single-page.

**Comment by rose-coste** [comment]
Thanks, @ktbartholomew; that's what I wondered. Closing this.

**Comment by meker12** [comment]
I was able to delete it from my local clone of the core infrastructure guide, and the contents looks OK. 

I didn't think it did anything because the conf.py file points to the  index.rst as the master_doc.  But maybe the deconst build uses the _toc.rst for something else.

**Pull request closed without merging**
