### PR TITLE
fixing up the table in the intro

### PR DESCRIPTION
**Pull request by ktbartholomew**
The ReStructuredText on the main page was rendering as several separate tables instead of one, combined table. This PR corrects that issue.

### CODE REVIEW

**Comment by rose-coste** [comment]
Actually, I was sneaking up on handling each little box as a separate include, to then also include on some other pages; just hadn't been back for the next round. I'll work this out later.

---rose

**Comment by rose-coste** [comment]
The more I think about it, the more I'm sure that the next thing I want to do here is easier if these 4 boxes stay separate; I'd soon undo what you did. Let's leave it alone for now.

**Comment by ktbartholomew** [comment]
@rose-coste I need to style this content for inclusion in DRC, and this is a very high-visibility part of that content. The sooner you can fill me in on what you plan to do here, the sooner I can write the corresponding styles.

**Comment by rose-coste** [comment]
OK, I thought this was just about personal preference; I don't mean to hold up the project while I think. I'm out to do interviews the rest of the afternoon. Please fix this page to please yourself for now; I'll go back to my original plan of leaving it be until some later time when I can experiment more.

**Comment by rose-coste** [comment]
Merging this now; thanks. 
https://github.com/rackerlabs/docs-core-infra-user-guide/issues/154 is about using these logos, introduced on the front page, throughout. We're doing a good job of that in the figures now, thanks to @DonNateR. Beyond that, we can deal with other ornamentation later, perhaps partly by including some version of each product-specific table row as a box at the bottom of key product-specific pages.

**Pull request merged**
