### PR TITLE
JIRA:ESC-235 removing Vyatta references and introducing concept of GW instance

### PR DESCRIPTION
**Pull request by inflatador**
Fixes JIRA:ESC-235

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-bba7340157/docs/user-guides/infrastructure/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-1574e99cd9/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-f5ef12745d/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-4f89df1e2d/docs/user-guides/infrastructure/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-76e128ede1/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-77c8e6adf2/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-21f037700a/docs/user-guides/infrastructure/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-ceb153b36b/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-3c133cb8d7/docs/user-guides/infrastructure/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-2dab1d9a2b/docs/user-guides/infrastructure/)

**Comment by cyrichardson** [comment]
@inflatador All my minor changes are just Style Guide-ish changes. Please check them and see if you agree with them. 

If you are ready and would like for me to merge the PR, please just let me know. 

Thanks for your docs contribution!

**Comment by cyrichardson** [comment]
From how-to channel:

Brian King [11:34 AM]
@catherine everything looks great, feel free to merge when ready. Thanks again!

**Pull request merged**
